#:kivy 2.1.0

RootWidget:
    # import container
    container: container

    # fill the container
    BoxLayout:
        id: container
        orientation: 'vertical'
        padding: 0
        spacing: 2

        Label:
            text: 'canvas3'
        Label:
            text: 'texto3'

        # Footer
        BoxLayout:
            orientation: 'horizontal'
            padding: 0
            spacing: 1
            size_hint_y: None
            height: '36dp'
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.5, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: '1.3 Dos líneas rectas'
            Button:
                size_hint_x: None
                width: self.height
                text: '<--'
                on_release: app.next_screen('1-2')
            Button:
                size_hint_x: None
                width: self.height
                text: '-->'
                on_release: app.next_screen('1-4')

