#:kivy 2.1.0

RootWidget:
    # import container
    container: container
    # fullscreen: True

    # main window
    BoxLayout:
        orientation: 'vertical'
        padding: 0
        spacing: 2

        # top menu
        BoxLayout:
            orientation: 'horizontal'
            padding: 0
            spacing: 2
            size_hint_y: None
            height: '36dp'

            Button:
                size_hint_x: None
                width: self.height
                text: " ? "
                on_release: app.next_screen('1')

            # Display selectors for sections and sub-sections
            # The number will be used to open the corresponding file
            Carousel:
                id: carousel
                loop: False
                Spinner:
                    text: "Capítulo 1"
                    values: "1 PUNTOS", "1-1 Conceptos", "1-2 Línea recta", "1-3 Dos líneas rectas", "1-4 Tres líneas rectas"
                    on_text: app.next_screen(self.text)
                Spinner:
                    text: "Capítulo 2"
                    values: "2 POLÍGONOS", "2-1 De tres lados", "2-2 De cuatro lados", "2-3 De más lados"
                    on_text: app.next_screen(self.text)
                Spinner:
                    text: "Capítulo 3"
                    values: "3 LÍNEAS CURVAS", "3-1 Cerradas", "3-2 Círculos", "3-3 Abiertas"
                    on_text: app.next_screen(self.text)
                Spinner:
                    text: "Capítulo 4"
                    values: "4 CONCEPTOS 3D", "4-1 Puntos", "4-2 Líneas", "4-3 Polígonos", "4-4 Planos", "4-5 Sólidos"
                    on_text: app.next_screen(self.text)
            Button:
                size_hint_x: None
                width: self.height
                text: '<--'
                on_release: carousel.load_previous()
            Button:
                size_hint_x: None
                width: self.height
                text: '-->'
                on_release: carousel.load_next()

        # create container to show content
        BoxLayout:
            canvas.before:
                Color:
                    rgba: 0.0, 0.0, 1, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            id: container

