#:kivy 1.4

BoxLayout:
    #canvas.before:
    #    Color:
    #        rgba: 0, 1, 0, 1
    #    Rectangle:
    #        # self here refers to the widget i.e FloatLayout
    #        pos: self.pos
    #        size: self.size
    orientation: 'vertical'
    padding: 2
    spacing: 2

    BoxLayout:
        orientation: 'horizontal'
        padding: 2
        spacing: 2
        Spinner:
            text: "Puntos"
            values: "Conceptos", "Línea recta", "2 líneas rectas", "3 líneas rectas"
            size_hint: (1, None)
            size: (100, 44)
        Spinner:
            text: "Polígonos"
            values: "3 lados", "4 lados", "Más lados"
            size_hint: (1, None)
            size: (100, 44)
        Spinner:
            text: "Líneas curvas"
            values: "Cerradas", "Círculos", "Abiertas"
            size_hint: (1, None)
            size: (100, 44)
        Spinner:
            text: "Conceptos 3D"
            values: "Puntos", "Líneas", "Polígonos", "Planos", "Sólidos"
            size_hint: (1, None)
            size: (100, 44)

    ProgressBar:
        id: bar
        value: 140
        max: 300
		size_hint: (1, None)
        size: (100, 44)
    Slider:
        id: slider
        max: 200
        value: 140 
		size_hint: (1, None)
        size: (100, 44)
        on_value: slider.value = self.value
    Slider:
        on_value: slider.value = self.value
		size_hint: (1, None)
        size: (100, 44)
    Button:
        text: "Button 1"
		size_hint: (1, None)
        size: (100, 44)
        background_color: .7, .7, 1, 1
        on_press: self.text = 'pressed'
        on_release: self.text = 'Button 4'
    RstDocument:
		size_hint: (1, 3)
 	    size: (100, 44)
        text: ".. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\nAnd this is a reference to top_::\n\n    $ print('Hello world')\n"

    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10
        Button:
            text: "Button 3"
            size_hint: 1, 2