#:kivy 2.1

RootWidget:
    # import container
    container: container

    GridLayout:
        cols: 1
        #row_force_default: True
        #row_default_height: 40
        GridLayout:
            rows: 1
            #row_force_default: True
            #row_default_height: 40
            size_hint: (1, 0.1)        
            Spinner:
                text: "Puntos"
                values: "Conceptos", "Línea recta", "2 líneas rectas", "3 líneas rectas"
            Spinner:
                text: "Polígonos"
                values: "3 lados", "4 lados", "Más lados"
            Spinner:
                text: "Líneas curvas"
                values: "Cerradas", "Círculos", "Abiertas"
            Spinner:
                text: "Conceptos 3D"
                values: "Puntos", "Líneas", "Polígonos", "Planos", "Sólidos"
            Button:
                text: "Help"
                #on_press: comments.text
        GridLayout:
            cols: 2
            size_hint: (1, 2)
            Label:
                canvas.before:
                    Color:
                        rgba: 0.8, 0.8, 0.9, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: "Canvas"
                size_hint: (0.9, 0.9)
            Slider:
                orientation: 'vertical'
                size_hint: (0.075, 1)
            Slider:
                size_hint: (1, 0.075)
        RstDocument:
            id: container
            size_hint: (1, 1)
            text: ".. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n"
