#:kivy 1.8.0
#:import datetime datetime

RootWidget:
    # import container
    container: container

    # fill the container
    RstDocument:
        # create container
        id: container
        size_hint: (1, 1)
        text: ".. _top:\n\nHello world 2 \n==============\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n.. _top:\n\nHello world\n===========\n\nThis is an **emphased text**, some ``interpreted text``.\n"
