#:kivy 2.1.0

RootWidget:
    # import container
    container: container

    # fill the container
    BoxLayout:
        id: container
        orientation: 'vertical'
        RstDocument:
            canvas.before:
                Color:
                    rgba: intro_background_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            source: rst_files_folder + "intro.rst"
